@api = http://localhost:3000/api/v1

//**********USER REQUEST**********


### GET a user by ID
GET {{api}}/user/12


### GET get all users
GET {{api}}/users/


### POST create user
POST {{api}}/user/new
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@correounivalle.edu.co",
    "password": "12345678"
}


### PUT  update user
PUT {{api}}/user/update/1
Content-Type: application/json

{
     "name": "my new name",
    "email": "newEmail@correounivalle.edu.co",
    "password": "12345678"
}


### DELETE delete user
DELETE {{api}}/user/delete/1

//**********QUESTION REQUEST**********


### GET a question by ID
GET {{api}}/question/#id


### GET  multiple questions
GET {{api}}/questions/


### Create Question
POST {{api}}/question/new/
Content-Type: application/json

{
    "idAutor": "12345678",
    "question": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua?",
    "tag": "Math"
}


### Update Question
PUT {{api}}/question/update/5fe7b7b8e5ba032e54807d9d
Content-Type: application/json

{
    "question": "I am updating a Question. ok?",
    "tag": "Something"
}


### DELETE question
DELETE {{api}}/question/delete/5fe7b5c8642bde2ce1b181fc