@api = http://localhost:3000/api/v1

### GET a user by ID
GET {{api}}/user/6036b2bee7470b2978293db1


### GET get all users
GET {{api}}/users/


### SIGNUP
POST {{api}}/auth/signup
Content-Type: application/json

{
    "name": "Rayo McQueen",
    "email": "rayo.maqueen@correounivalle.edu.co",
    "password": "12345678",
    "password2": "12345678"
}

### LOGIN
POST {{api}}/auth/login
Content-Type: application/json

{
    "email": "rayo.maqueen@correounivalle.edu.co",
    "password": "12345678"
}

### LOGOUT
GET {{api}}/auth/logout


### PROFILE
GET {{api}}/auth/profile


### PUT  update user
PUT {{api}}/auth/update/#id
Content-Type: application/json

{
     "name": "my new name",
    "email": "newEmail@correounivalle.edu.co",
    "password": "12345678",
    "location": "Cali Valle del Cauca"
}


### DELETE delete user
DELETE {{api}}/user/delete/#id